on: [push]

jobs:
  hello_test:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world action step
      id: hello
      uses: javixeneize/action_test@v1.3
      with:
        who-to-greet: 'My name'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
